# Generated by Django 5.0.4 on 2024-07-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='user_id',
            new_name='user',
        ),
    ]
